import turtle

wn=turtle.Screen()
wn.bgcolor("yellow")

turtle=turtle.Turtle(shape="turtle")
turtle.speed(100)

#roof
turtle.color("black","red")
turtle.begin_fill()
turtle.forward(300)
turtle.left(120)
turtle.forward(300)
turtle.left(120)
turtle.forward(300)
turtle.end_fill()

#house
turtle.color("black","green")
turtle.begin_fill()
turtle.left(30)
turtle.forward(300)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(300)
turtle.left(135)
turtle.end_fill()

turtle.up()
turtle.setposition(270,-30)
turtle.down()

#window
turtle.color("black","blue")
turtle.begin_fill()
turtle.left(45)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(40)
turtle.left(45)
turtle.end_fill()

#door
turtle.color("black","brown")
turtle.begin_fill()
turtle.up()
turtle.setposition(105,-160)
turtle.down()
turtle.left(45)
turtle.forward(120)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.up()
turtle.setposition(115,-220)
turtle.down()
turtle.color("black","pink")
turtle.begin_fill()
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()

turtle.done()
